### ISSUE TITLE
'a_b_c' precedes 'a_b'

### ISSUE THREAD

**Issue by brynpickering** [ue/alphabetical-sorter#3]
Currently, if you have a list which is `['a_b', 'a_b_c', 'a', 'b']` it will order it as `['a_b_c', 'a_b', 'a', 'b']`. My expectation would be `['a', 'a_b', 'a_b_c', 'b']`. Could this be changed/added as an option in settings?

**Comment by ue** [comment]
Thanx for your feed back @brynpickering .
The algorithm order by ascii code. So in this case its working according to '_' underscore, its not only calculate latter ascii. There for output is  `['a_b_c', 'a_b', 'a', 'b']`. But I can change the algorithm, thats make sense.
