### ISSUE TITLE
Sometimes sorting now working properly. Random order after sort.

### ISSUE THREAD

**Issue by vijayhardaha** [ue/alphabetical-sorter#8]
![sort issue](https://user-images.githubusercontent.com/25227317/74471716-b5def380-4ec6-11ea-852e-d1c9e9e37f2c.gif)

**Comment by tpiekarski** [comment]
Nice gif, but please could you provide the file (or the part shown) and some more details like version of Code, so it could be reproduced. :smile:

**Comment by vijayhardaha** [comment]
Hey,
I sorted this issue. it was because of some kind of whitespace conflict with formatter extension. Your extension works fine. 👍
